/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_SYSTEM_H_RPCGEN
#define _FILE_SYSTEM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct write_data {
	char *file_name;
	int amount;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct write_data write_data;

struct read_data {
	char *file_name;
	int pos;
	int amount;
};
typedef struct read_data read_data;

struct file_data {
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct file_data file_data;

#define file_system 0x20000001
#define display_ver 1

#if defined(__STDC__) || defined(__cplusplus)
#define write 1
extern  int * write_1(write_data *, CLIENT *);
extern  int * write_1_svc(write_data *, struct svc_req *);
#define read 2
extern  file_data * read_1(read_data *, CLIENT *);
extern  file_data * read_1_svc(read_data *, struct svc_req *);
extern int file_system_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define write 1
extern  int * write_1();
extern  int * write_1_svc();
#define read 2
extern  file_data * read_1();
extern  file_data * read_1_svc();
extern int file_system_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_write_data (XDR *, write_data*);
extern  bool_t xdr_read_data (XDR *, read_data*);
extern  bool_t xdr_file_data (XDR *, file_data*);

#else /* K&R C */
extern bool_t xdr_write_data ();
extern bool_t xdr_read_data ();
extern bool_t xdr_file_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_SYSTEM_H_RPCGEN */
