/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file_system.h"

bool_t
xdr_write_data (XDR *xdrs, write_data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->file_name, 32))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->amount))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->data, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_data (XDR *xdrs, read_data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->file_name, 32))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pos))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->amount))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_data (XDR *xdrs, file_data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->data, ~0))
		 return FALSE;
	return TRUE;
}
