/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file_system.h"

//Funcion para concatenar la direccion del archivo a la de la carpeta raiz del file system
char* getAddress(char* file){
  char* address = (char*) malloc(sizeof(char) * 100);
  strcpy(address, "FS/");
  strcat(address,file);
  return address;
}

int *
write_1_svc(write_data *argp, struct svc_req *rqstp)
{
	static int i = -1;

	FILE* fp;
  char* address = (char*) malloc(sizeof(char) * 100);
  address = getAddress(argp->file_name);

  fp = fopen(address, "a");
  if(fp) {
    for (i = 0; i < argp->amount && i < strlen(argp->data); i++) {
      fputc(argp->data[i],fp);
    }
  }

	return &i;
}

char **
read_1_svc(read_data *argp, struct svc_req *rqstp)
{
	static char * file;

	FILE* fp;
  char* address = (char*) malloc(sizeof(char) * 100);
  address = getAddress(argp->file_name);

  file = (char*) malloc(sizeof(char)*argp->amount);
  fp = fopen(address, "r");
  fseek(fp, argp->pos, 0);
  if(fp) {
    fgets(file, argp->amount, fp);
  }
  fclose(fp);

	return &file;
}
