/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file_system.h"


void
file_system_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	write_data  write_1_arg;
	char * *result_2;
	read_data  read_1_arg;

	#ifndef	DEBUG
		clnt = clnt_create (host, file_system, display_ver, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */
	
	write_1_arg.file_name = "hola.txt\0";
	write_1_arg.amount = 10;
	write_1_arg.data = "aaaaaaabbbbbbc\0";

/*
	result_1 = write_1(&write_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
*/		
	read_1_arg.file_name = "hola.txt\0";
	read_1_arg.amount = 10;
	read_1_arg.pos = 2;

	result_2 = read_1(&read_1_arg, clnt);
	/*
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%s",*result_2);
	*/

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	file_system_1 (host);
exit (0);
}
